version: '3.9'

services:
  analytics-datastore-elastic-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
    environment:
      node.name: es01
      discovery.type: single-node
      bootstrap.memory_lock: 'true'
      xpack.security.enabled: 'true'
      xpack.monitoring.collection.enabled: 'true'
      ES_JAVA_OPTS: -Xms4096m -Xmx4096m
      search.max_buckets: 1000000
      search.default_search_timeout: -1
      path.repo: /backups/elasticsearch
      ES_LOGSTASH_SYSTEM: ${ES_LOGSTASH_SYSTEM:-dev_password_only}
      ES_APM_SYSTEM: ${ES_APM_SYSTEM:-dev_password_only}
      ES_REMOTE_MONITORING_USER: ${ES_REMOTE_MONITORING_USER:-dev_password_only}
      ES_ELASTIC: ${ES_ELASTIC:-dev_password_only}
      ES_KIBANA_SYSTEM: ${ES_KIBANA_SYSTEM:-dev_password_only}
      ES_BEATS_SYSTEM: ${ES_BEATS_SYSTEM:-dev_password_only}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
      - /backups/elasticsearch:/backups/elasticsearch

volumes:
  es-data:
