---
image: jembi/platform
defaultEnvironment: swarm
disableKubernetes: true
disableIG: true
packages:
    - id: interoperability-layer-openhim
      name: Interoperability Layer - OpenHIM
    - id: reverse-proxy-nginx
      name: Reverse Proxy - NGINX
    - id: fhir-datastore-hapi-fhir
      name: FHIR Data Store - HAPI-FHIR
    - id: message-bus-kafka
      name: Message Bus - Kafka
    - id: elastic-analytics-elasticsearch-kibana
      name: Elastic-Analytics - ElasticSearch and Kibana
    - id: elastic-pipeline-logstash
      name: Elastic-Pipeline - LogStash
    - id: elastic-monitoring-metricbeats-filebeats
      name: Elastic Monitoring - MetricBeats and FileBeats
    - id: system-monitoring-prometheus-grafana
      name: System Monitoring - Prometheus and Grafana
