version: '3.9'

services:
  await-helper:
    image: jembi/await-helper:1.0.0
    deploy:
      mode: replicated-job
      replicas: 1
      restart_policy:
        condition: none
    command: 'http://dashboard-visualiser-jsreport:5488/'
