version: '3.3'

services:
  hapi-proxy:
    image: jembi/springproxyserver:20211217-170809.3f57ef5
    hostname: hapi-proxy
    environment:
      HAPI_SERVER_URL: ${HAPI_SERVER_URL:-http://hapi-fhir:8080/fhir}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS:-kafka:9092}
      HAPI_SERVER_VALIDATE_FORMAT: ${HAPI_SERVER_VALIDATE_FORMAT:-NONE}
    deploy:
      replicas: 1
