version: '3.9'

services:
  mpi-checker:
    image: jembi/openhim-mediator-mpi-checker:${MPI_CHECKER_VERSION}
    environment:
      CLIENT_REGISTRY_URL: ${CLIENT_REGISTRY_URL}
      FHIR_SERVER_URL: ${FHIR_SERVER_URL}
      KAFKA_URL: ${KAFKA_URL}
      KAFKA_TOPIC: ${KAFKA_BUNDLE_TOPIC}
      KAFKA_PATIENT_TOPIC: ${KAFKA_PATIENT_TOPIC}
      REGISTER_MEDIATOR: ${REGISTER_MEDIATOR}
      OPENHIM_MEDIATOR_URL: ${OPENHIM_MEDIATOR_URL}
      TRUST_SELF_SIGNED: ${TRUST_SELF_SIGNED}

  mpi-updater:
    image: jembi/openhim-mediator-mpi-updater:${MPI_UPDATER_VERSION}
    environment:
      CLIENT_REGISTRY_URL: ${CLIENT_REGISTRY_URL}
      FHIR_SERVER_URL: ${FHIR_SERVER_URL}
      KAFKA_URL: ${KAFKA_URL}
      KAFKA_TOPIC: ${KAFKA_BUNDLE_TOPIC}
      KAFKA_PATIENT_TOPIC: ${KAFKA_PATIENT_TOPIC}
      OPENHIM_MEDIATOR_URL: ${OPENHIM_MEDIATOR_URL}
      TRUST_SELF_SIGNED: ${TRUST_SELF_SIGNED}
      REGISTER_MEDIATOR: ${REGISTER_MEDIATOR}
