version: '3.9'

services:
  job-scheduler-ofelia:
    image: mcuadros/ofelia:v0.3.6
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      ofelia.enabled: "true"
      ofelia.job-local.placeholder-job.schedule: "@hourly"
      ofelia.job-local.placeholder-job.command: "date"
