version: '3.3'

services:
  openhim-core:
    deploy:
      replicas: 1

  openhim-console:
    deploy:
      replicas: 1
    configs:
      - source: console.config
        target: /usr/share/nginx/html/config/default.json

  hapi-fhir:
    deploy:
      replicas: 1

  hapi-db:
    deploy:
      replicas: 1

  hapi-proxy:
    deploy:
      replicas: 1

configs:
  console.config:
    file: ./importer/volume/default.json
