version: '3.3'

services:
  openhim-core:
    deploy:
      placement:
        max_replicas_per_node: 1
      replicas: 2

  openhim-console:
    configs:
      - source: console.config
        target: /usr/share/nginx/html/config/default.json

configs:
  console.config:
    file: ./importer/volume/default.json
