version: '3.3'

services:
  openhim-core:
    deploy:
      placement:
        constraints:
          - "node.labels.name==primary-1"

  openhim-console:
    deploy:
      placement:
        constraints:
          - "node.labels.name==primary-2"
    configs:
      - source: console.config
        target: /usr/share/nginx/html/config/default.json

configs:
  console.config:
    file: ./importer/volume/default.json
