version: '3.3'

services:
  openhim-core:
    image: jembi/openhim-core:7
    environment:
      - mongo_url=mongodb://mongo-1:27017,mongo-2:27017,mongo-3:27017/openhim?replicaSet=mongo-set
      - mongo_atnaUrl=mongodb://mongo-1:27017,mongo-2:27017,mongo-3:27017/openhim?replicaSet=mongo-set
      - api_authenticationTypes=["token", "basic"]
      - authentication_enableCustomTokenAuthentication=true

  openhim-console:
    image: jembi/openhim-console:1.14.4
    depends_on:
      - openhim-core
    configs:
      - source: console.config
        target: /usr/share/nginx/html/config/default.json

  hapi-proxy:
    image: jembi/springproxyserver:20211217-170809.3f57ef5
    hostname: hapi-proxy
    environment:
      HAPI_SERVER_URL: 'http://hapi-fhir:8080/fhir'
      KAFKA_BOOTSTRAP_SERVERS: 'kafka:9092'
      HAPI_SERVER_VALIDATE_FORMAT: 'NONE'

volumes:
  instant:
    external: true

configs:
  console.config:
    file: ./importer/volume/default.json
