version: '3.3'

services:
  openhim-core:
    image: jembi/openhim-core:7
    environment:
      - mongo_url=mongodb://mongo-1:27017,mongo-2:27017,mongo-3:27017/openhim?replicaSet=mongo-set
      - mongo_atnaUrl=mongodb://mongo-1:27017,mongo-2:27017,mongo-3:27017/openhim?replicaSet=mongo-set
      - api_authenticationTypes=["token", "basic"]
      - authentication_enableCustomTokenAuthentication=true

  openhim-console:
    image: jembi/openhim-console:1.14.4
    depends_on:
      - openhim-core
volumes:
  instant:
    external: true
