---
- hosts: leader
  tasks:
    # This task is not split into a role as the swarm token context is lost outside of this playbook
    - name: Destroy an existing swarm
      community.docker.docker_swarm:
        state: absent
        force: true

- hosts: managers
  tasks:
    - name: Remove manager nodes from swarm network
      community.docker.docker_swarm:
        state: absent
        force: true

- hosts: workers
  tasks:
    - name: Remove worker nodes from swarm network
      community.docker.docker_swarm:
        state: absent
        force: true
