version: '3.9'

services:
  fhir-ig-importer-mediator:
    ports:
      - target: 3333
        published: 3333
        mode: host
  fhir-ig-importer-ui:
    ports:
      - target: 8080
        published: 3000
        mode: host
      - target: 8081
        published: 3003
        mode: host
