version: '3.9'

services:
  postgres-1:
    deploy:
      placement:
        constraints:
          - "node.labels.name==node-1"
      resources:
        limits:
          cpus: ${HF_POSTGRES_CPU_LIMIT:-0.8}
          memory: ${HF_POSTGRES_MEMORY_LIMIT:-3G}
        reservations:
          cpus: ${HF_POSTGRES_CPU_RESERVE:-0.05}
          memory: ${HF_POSTGRES_MEMORY_RESERVE:-500M}

  postgres-2:
    deploy:
      placement:
        constraints:
          - "node.labels.name==node-2"
      resources:
        limits:
          cpus: ${HF_POSTGRES_CPU_LIMIT:-0.8}
          memory: ${HF_POSTGRES_MEMORY_LIMIT:-3G}
        reservations:
          cpus: ${HF_POSTGRES_CPU_RESERVE:-0.05}
          memory: ${HF_POSTGRES_MEMORY_RESERVE:-500M}

  postgres-3:
    deploy:
      placement:
        constraints:
          - "node.labels.name==node-3"
      resources:
        limits:
          cpus: ${HF_POSTGRES_CPU_LIMIT:-0.8}
          memory: ${HF_POSTGRES_MEMORY_LIMIT:-3G}
        reservations:
          cpus: ${HF_POSTGRES_CPU_RESERVE:-0.05}
          memory: ${HF_POSTGRES_MEMORY_RESERVE:-500M}
