version: '3.9'

services:
  postgres-1:
    image: bitnami/postgresql-repmgr:14
    environment:
      POSTGRESQL_PASSWORD: instant101
      POSTGRESQL_USERNAME: admin
      POSTGRESQL_DATABASE: hapi
      REPMGR_NODE_NETWORK_NAME: postgres-1
      REPMGR_PASSWORD: instant101
      REPMGR_RECONNECT_INTERVAL: 3
      REPMGR_NODE_NAME: postgres-1
      REPMGR_PRIMARY_HOST: ${REPMGR_PRIMARY_HOST:-postgres-1}
      REPMGR_PARTNER_NODES: ${REPMGR_PARTNER_NODES:-postgres-1,postgres-2,postgres-3}
    volumes:
      - 'hapi-postgres-1-data:/bitnami/postgresql'
    deploy:
      replicas: 1

  postgres-2:
    image: bitnami/postgresql-repmgr:14
    environment:
      POSTGRESQL_PASSWORD: instant101
      POSTGRESQL_USERNAME: admin
      POSTGRESQL_DATABASE: hapi
      REPMGR_NODE_NETWORK_NAME: postgres-2
      REPMGR_PASSWORD: instant101
      REPMGR_RECONNECT_INTERVAL: 3
      REPMGR_NODE_NAME: postgres-2
      REPMGR_PRIMARY_HOST: ${REPMGR_PRIMARY_HOST:-postgres-1}
      REPMGR_PARTNER_NODES: ${REPMGR_PARTNER_NODES:-postgres-1,postgres-2,postgres-3}
    volumes:
      - 'hapi-postgres-2-data:/bitnami/postgresql'
    deploy:
      replicas: 1

  postgres-3:
    image: bitnami/postgresql-repmgr:14
    environment:
      POSTGRESQL_PASSWORD: instant101
      POSTGRESQL_USERNAME: admin
      POSTGRESQL_DATABASE: hapi
      REPMGR_NODE_NETWORK_NAME: postgres-3
      REPMGR_PASSWORD: instant101
      REPMGR_RECONNECT_INTERVAL: 3
      REPMGR_NODE_NAME: postgres-3
      REPMGR_PRIMARY_HOST: ${REPMGR_PRIMARY_HOST:-postgres-1}
      REPMGR_PARTNER_NODES: ${REPMGR_PARTNER_NODES:-postgres-1,postgres-2,postgres-3}
    volumes:
      - 'hapi-postgres-3-data:/bitnami/postgresql'
    deploy:
      replicas: 1

volumes:
  hapi-postgres-1-data:
  hapi-postgres-2-data:
  hapi-postgres-3-data:
