version: '3.3'

services:
  hapi-fhir:
    deploy:
      placement:
        constraints:
          - "node.labels.name==primary-1"

  hapi-db:
    deploy:
      placement:
        constraints:
          - "node.labels.name==primary-2"
