version: '3.9'

services:
  hapi-fhir:
    image: hapiproject/hapi:v5.7.0
    environment:
      - spring.datasource.url=jdbc:postgresql://${POSTGRES_REPLICA_SET:-postgres-1:5432}/hapi
      - spring.datasource.username=admin
      - spring.datasource.password=instant101
      - spring.datasource.driverClassName=org.postgresql.Driver
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL95Dialect
      - hapi.fhir.allow_external_references=true
      - hapi.fhir.bulk_export_enabled=true
      - hapi.fhir.enable_repository_validating_interceptor=true
      - JAVA_TOOL_OPTIONS=-Xmx2g
      - CATALINA_OPTS=-Xmx2g
    deploy:
      replicas: ${HAPI_FHIR_INSTANCES}
      placement:
        max_replicas_per_node: 1
      resources:
        limits:
          cpus: ${HAPI_FHIR_CPU_LIMIT:-0.8}
          memory: ${HAPI_FHIR_MEMORY_LIMIT:-3G}
        reservations:
          cpus: ${HAPI_FHIR_CPU_RESERVE:-0.05}
          memory: ${HAPI_FHIR_MEMORY_RESERVE:-500M}

  ofelia_postgres_backup:
      image: mcuadros/ofelia:v0.3.6
      deploy:
        replicas: 1
      command: daemon --docker
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - /home/nour/Hexastack/platform/backups/postgres/:/tmp/
      depends_on:
        - hapi-fhir
      labels:
        ofelia.enabled: "true"
        ofelia.job-run.backup_postgres.schedule: "@every 15s"
        ofelia.job-run.backup_postgres.image: "jembi/psql-client:test"
        ofelia.job-run.backup_postgres.volume: '["/home/nour/Hexastack/platform/backups/postgres/:/tmp/","/var/run/docker.sock:/var/run/docker.sock:ro"]'
        # ofelia.job-run.backup_postgres.command: 'PGPASSWORD=instant101 /usr/bin/pg_dump --file "/tmp/test_backup__postgres" --host "postgres-1" --port "5432" --username "admin" --verbose --format=c --blobs "hapi"'
        ofelia.job-run.backup_postgres.command: "sleep 500"
        ofelia.job-run.backup_postgres.dir: "/tmp/"
