version: '3.9'

services:
  postgres-1:
    deploy:
      placement:
        constraints:
          - "node.labels.name==node-1"

  postgres-2:
    deploy:
      placement:
        constraints:
          - "node.labels.name==node-2"

  postgres-3:
    deploy:
      placement:
        constraints:
          - "node.labels.name==node-3"
