version: '3.9'

services:
  postgres-1:
    image: bitnami/postgresql-repmgr:14
    environment:
      POSTGRESQL_PASSWORD: ${HF_POSTGRESQL_PASSWORD:-instant101}
      POSTGRESQL_USERNAME: ${HF_POSTGRESQL_USERNAME:-admin}
      POSTGRESQL_DATABASE: ${HF_POSTGRESQL_DATABASE:-hapi}
      REPMGR_NODE_NETWORK_NAME: postgres-1
      REPMGR_PASSWORD: ${REPMGR_PASSWORD:-instant101}
      REPMGR_RECONNECT_INTERVAL: 3
      REPMGR_NODE_NAME: postgres-1
      REPMGR_PRIMARY_HOST: ${REPMGR_PRIMARY_HOST:-postgres-1}
      REPMGR_PARTNER_NODES: ${REPMGR_PARTNER_NODES:-postgres-1}
    volumes:
      - 'hapi-postgres-1-data:/bitnami/postgresql'
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: ${HF_POSTGRES_CPU_LIMIT:-0.8}
          memory: ${HF_POSTGRES_MEMORY_LIMIT:-3G}
        reservations:
          cpus: ${HF_POSTGRES_CPU_RESERVE:-0.05}
          memory: ${HF_POSTGRES_MEMORY_RESERVE:-500M}
    networks:
      pg_backup_net: {}

  ofelia-postgres-backup:
    image: mcuadros/ofelia:v0.3.6
    deploy:
      replicas: 1
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /backups/:/tmp/
    depends_on:
      - hapi-fhir
    labels:
      ofelia.enabled: 'true'
      ofelia.job-run.backup_postgres.schedule: '@every 24h'
      ofelia.job-run.backup_postgres.image: alpine:3.15.5
      ofelia.job-run.backup_postgres.network: pg_backup
      ofelia.job-run.backup_postgres.volume: '["/backups/:/tmp/","/var/run/docker.sock:/var/run/docker.sock:ro"]'
      ofelia.job-run.backup_postgres.command: sh -c 'apk add --no-cache postgresql-client>14.4; PGPASSWORD=${HF_POSTGRESQL_PASSWORD:-instant101} /usr/bin/pg_dump --file "/tmp/hf_pg_backup_$$(date +%s)" --host "postgres-1" --port "5432" --username ${HF_POSTGRESQL_USERNAME:-admin} --blobs ${HF_POSTGRESQL_DATABASE:-hapi}'
      ofelia.job-run.backup_postgres.dir: /tmp/

volumes:
  hapi-postgres-1-data:


networks:
  pg_backup_net:
    name: pg_backup
    driver: overlay
    attachable: true
