version: '3.9'

services:
  jempi-alpha-01:
    deploy:
      placement:
        constraints:
          - node.labels.name == node-1

  jempi-alpha-02:
    deploy:
      placement:
        constraints:
          - node.labels.name == node-2

  jempi-alpha-03:
    deploy:
      placement:
        constraints:
          - node.labels.name == node-3

  jempi-ratel:
    deploy:
      placement:
        constraints:
          - node.labels.name == node-1
