version: '3.9'

services:

  jempi-controller:
    ports:
      - published: 50020
        target: 50000
        protocol: tcp
        mode: host

  jempi-linker:
    ports:
      - published: 50010
        target: 50000
        protocol: tcp
        mode: host

  jempi-postgresql-01:
    ports:
      - published: 5435
        target: 5432
        mode: host
