version: '3.9'

services:
  jempi-api:
    image: jembi/jempi-api:${JEMPI_API_IMAGE_TAG}
    environment:
      KC_REALM_NAME: ${KC_REALM_NAME}
      KC_JEMPI_CLIENT_ID: ${KC_JEMPI_CLIENT_ID}
      KC_JEMPI_CLIENT_SECRET: ${KC_JEMPI_CLIENT_SECRET}
      KC_API_URL: ${KC_API_URL}
      KC_JEMPI_ROOT_URL: ${KC_JEMPI_ROOT_URL}
      JEMPI_SESSION_SECRET: ${JEMPI_SESSION_SECRET}
      kafka.bootstrap.servers: ${KAFKA_HOSTS}
      JEMPI_FILE_IMPORT_MAX_SIZE_BYTE: ${JEMPI_FILE_IMPORT_MAX_SIZE_BYTE}
      JEMPI_SESSION_SECURE: ${JEMPI_SESSION_SECURE}
      JEMPI_SESSION_DOMAIN_NAME: ${DOMAIN_NAME}
    deploy:
      replicas: 1
      resources:
        limits:
          memory: ${JEMPI_API_MEMORY_LIMIT}
        reservations:
          memory: ${JEMPI_API_MEMORY_RESERVE}
    networks:
      reverse-proxy:
      keycloak:
      kafka:
      default:


networks:
  reverse-proxy:
    name: reverse-proxy_public
    external: true
  keycloak:
    name: keycloak_public
    external: true
  kafka:
    name: kafka_public
    external: true
  default:
