version: '3.9'

services:
  jempi-api:
    image: jembi/jempi-api:${JEMPI_API_IMAGE_TAG}
    environment:
      POSTGRESQL_USER: ${POSTGRESQL_USERNAME} 
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD} 
      POSTGRESQL_DATABASE: ${POSTGRESQL_DATABASE}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_HOSTS}
      KAFKA_APPLICATION_ID: ${KAFKA_APPLICATION_ID_API}
      DGRAPH_HOSTS: ${DGRAPH_HOSTS}
      DGRAPH_PORTS: ${DGRAPH_PORTS}
      HTTP_SERVER_PORT: ${HTTP_SERVER_PORT}
      LOG4J2_LEVEL: ${LOG4J2_LEVEL}
      LINKER_HOST: ${LINKER_HOST}
    volumes:
      - "jempi-shared-data:/app/csv"
    deploy:
      replicas: ${JEMPI_API_INSTANCES}
      resources:
        limits:
          memory: ${JEMPI_API_MEMORY_LIMIT}
        reservations:
          memory: ${JEMPI_API_MEMORY_RESERVE}
    networks:
      reverse-proxy:
      kafka:
      default:

volumes:
  jempi-shared-data: 

networks:
  reverse-proxy:
    name: reverse-proxy_public
    external: true
  kafka:
    name: kafka_public
    external: true
  default:
