version: '3.9'

services:
  jempi-em-calculator:
    image: jembi/jempi-em-calculator
    deploy:
      replicas: 1
      resources:
        limits:
          memory: ${EM_CALCULATOR_MEMORY_LIMIT}
        reservations:
          memory: ${EM_CALCULATOR_MEMORY_RESERVE}
