version: '3.9'

services:
  jempi-async-receiver:
    image: jembi/jempi-async-receiver:${ASYNC_RECEIVER_IMAGE_TAG}
    deploy:
      replicas: 1
      resources:
        limits:
          memory: ${ASYNC_RECEIVER_MEMORY_LIMIT}
        reservations:
          memory: ${ASYNC_RECEIVER_MEMORY_RESERVE}

  jempi-sync-receiver:
    image: jembi/jempi-sync-receiver:${SYNC_RECEIVER_IMAGE_TAG}
    deploy:
      replicas: 1
      resources:
        limits:
          memory: ${SYNC_RECEIVER_MEMORY_LIMIT}
        reservations:
          memory: ${SYNC_RECEIVER_MEMORY_RESERVE}

  jempi-pre-processor:
    image: jembi/jempi-pre-processor:${PRE_PROCESSOR_IMAGE_TAG}
    deploy:
      replicas: 1
      resources:
        limits:
          memory: ${PRE_PROCESSOR_MEMORY_LIMIT}
        reservations:
          memory: ${PRE_PROCESSOR_MEMORY_RESERVE}

  jempi-controller:
    image: jembi/jempi-controller:${CONTROLLER_IMAGE_TAG}
    deploy:
      replicas: 1
      resources:
        limits:
          memory: ${CONTROLLER_MEMORY_LIMIT}
        reservations:
          memory: ${CONTROLLER_MEMORY_RESERVE}

  jempi-em-calculator:
    image: jembi/jempi-em-calculator:${EM_CALCULATOR_IMAGE_TAG}
    deploy:
      replicas: 1
      resources:
        limits:
          memory: ${EM_CALCULATOR_MEMORY_LIMIT}
        reservations:
          memory: ${EM_CALCULATOR_MEMORY_RESERVE}

  jempi-linker:
    image: jembi/jempi-linker:${LINKER_IMAGE_TAG}
    deploy:
      replicas: 1
      resources:
        limits:
          memory: ${LINKER_MEMORY_LIMIT}
        reservations:
          memory: ${LINKER_MEMORY_RESERVE}
