version: '3.9'

services:
  jempi-async-receiver:
    image: jembi/jempi-async-receiver
    deploy:
      replicas: 1
      resources:
        limits:
          memory: ${ASYNC_RECEIVER_MEMORY_LIMIT}
        reservations:
          memory: ${ASYNC_RECEIVER_MEMORY_RESERVE}
