version: "3.9"

services:
  reverse-proxy-traefik:
    image: traefik:v3.0
    networks:
      - traefik
    ports:
      - 80:80
    command:
      - --log
      - --log.level=${LOG_LEVEL}
      - --providers.docker.exposedbydefault=false
      - --providers.swarm.useBindPortIP=true
      - --entrypoints.web.address=:80
      - --providers.docker.network=reverse-proxy-traefik_public
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
        reservations:
          cpus: "0.1"
          memory: 64M

networks:
  traefik:
    name: reverse-proxy-traefik_public
    external: true
