version: '3.9'

services:
  analytics-datastore-clickhouse:
    image: clickhouse/clickhouse-server
    ulimits:
      noFile: 262144
    volumes:
      - clickhouse-data:/var/lib/clickhouse/
    networks:
      public:
      private:

volumes:
  clickhouse-data:

networks:
  public:
    name: clickhouse_public
    external: true
  private:
