version: '3.9'

services:
  analytics-datastore-clickhouse-01:
    volumes:
      - clickhouse-configs-01:/etc/clickhouse-server/config.d/
    deploy: 
      placement: 
        constraints: 
          - "node.labels.name==node-1"

  analytics-datastore-clickhouse-02:
    image: clickhouse/clickhouse-server
    deploy: 
      placement: 
        constraints: 
          - "node.labels.name==node-2"
    ulimits:
      noFile: 262144
    volumes:
      - clickhouse-data-02:/var/lib/clickhouse/
      - clickhouse-configs-02:/etc/clickhouse-server/config.d/
      
  analytics-datastore-clickhouse-03:
    image: clickhouse/clickhouse-server
    deploy: 
      placement: 
        constraints: 
          - "node.labels.name==node-3"
    ulimits:
      noFile: 262144
    volumes:
      - clickhouse-data-03:/var/lib/clickhouse/        
      - clickhouse-configs-03:/etc/clickhouse-server/config.d/

volumes:
  clickhouse-data-02:
  clickhouse-data-03:
  clickhouse-configs-01:
    external: true
  clickhouse-configs-02:
    external: true
  clickhouse-configs-03:
    external: true

