version: '3.3'

services:
  zookeeper:
    deploy:
      placement:
        constraints:
          - "node.labels.name==primary-1"

  kafka:
    deploy:
      placement:
        constraints:
          - "node.labels.name==primary-1"

  kafdrop:
    deploy:
      placement:
        constraints:
          - "node.labels.name==primary-1"
