version: '3.9'

services:
  kafka-01:
    deploy:
      placement:
        constraints:
          - "node.labels.name==node-1"

  kafka-02:
    deploy:
      placement:
        constraints:
          - "node.labels.name==node-2"

  kafka-03:
    deploy:
      placement:
        constraints:
          - "node.labels.name==node-3"

