version: '3.9'

services:
  zookeeper-1:
    image: bitnami/zookeeper:3.7.0
    container_name: zookeeper-1
    environment:
     - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper-1-volume:/bitnami/zookeeper

  kafka:
    image: bitnami/kafka:3.1.0
    container_name: kafka
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-1:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_MESSAGE_MAX_BYTES=10485760
      - KAFKA_CFG_SOCKET_REQUEST_MAX_BYTES=20971520
    volumes:
      - kafka-volume:/bitnami/kafka

  kafdrop:
    image: obsidiandynamics/kafdrop:3.27.0
    container_name: kafdrop
    depends_on:
      - kafka
    environment:
      KAFKA_BROKERCONNECT: 'kafka:9092'
      JVM_OPTS: '-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify'
      CMD_ARGS: '--server.port=9013 --management.server.port=9013'

volumes:
  kafka-volume:
  zookeeper-1-volume:
