version: '3.9'

services:
  zookeeper:
    deploy:
      placement:
        constraints:
          - "node.labels.name==node-1"

  kafka:
    deploy:
      placement:
        constraints:
          - "node.labels.name==node-1"

  kafdrop:
    deploy:
      placement:
        constraints:
          - "node.labels.name==node-1"
