version: "3.9"

services:
  reprocess-mediator:
    image: ${REPROCESS_MEDIATOR_VERSION}
    networks:
      openhim:
      reprocess:
      openhim-mongo:
    environment:
      TRUST_SELF_SIGNED: ${TRUST_SELF_SIGNED}
      OPENHIM_MEDIATOR_URL: ${OPENHIM_MEDIATOR_URL}
      OPENHIM_USERNAME: ${OPENHIM_USERNAME}
      OPENHIM_PASSWORD: ${OPENHIM_PASSWORD}
      REGISTER_MEDIATOR: ${REGISTER_MEDIATOR}
      MONGODB_CONNECTION_STRING: ${MONGODB_CONNECTION_STRING}
      MONGODB_DIRECT_CONNECTION: ${MONGODB_DIRECT_CONNECTION}

  reprocess-mediator-ui:
    image: ${REPROCESS_MEDIATOR_UI_VERSION}
    networks:
      openhim:
      reprocess:
      reverse-proxy:
      traefik:
    environment:
      REPROCESSOR_API_BASE_URL: ${REPROCESSOR_API_BASE_URL}
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.docker.network=reverse-proxy-traefik_public
        - traefik.http.routers.reprocess-mediator-ui.rule=PathPrefix(`/reprocess-mediator-ui`)
        - traefik.http.services.reprocess-mediator-ui.loadbalancer.server.port=80
        - traefik.http.services.reprocess-mediator-ui.loadbalancer.server.url=http://reprocess-mediator-ui:80/jembi-reprocessor-mediator-microfrontend.js
        - traefik.http.routers.reprocess-mediator-ui.tls=true
        - traefik.http.routers.reprocess-mediator-ui.entrypoints=websecure
        - traefik.http.routers.reprocess-mediator-ui.middlewares=reprocess-mediator-ui-stripprefix
        - traefik.http.middlewares.reprocess-mediator-ui-stripprefix.stripprefix.prefixes=/reprocess-mediator-ui

networks:
  openhim:
    name: openhim_public
    external: true
  reprocess:
    name: reprocess_public
    external: true
  reverse-proxy:
    name: reverse-proxy_public
    external: true
  openhim-mongo:
    name: openhim_mongo_public
    external: true
  traefik:
    name: reverse-proxy-traefik_public
    external: true
