version: '3.9'

services:
  minio-01:
    image: ${MINIO_IMAGE}
    entrypoint: sh
    command: -c 'mkdir -p /data1/loki /data2/loki && minio server --console-address ":9001" --address ":9090" http://minio-0{1..${NUM_MINIO_SERVERS}}/data{1..2}'
    environment:
      MINIO_ROOT_USER: ${MO_SECURITY_ADMIN_USER}
      MINIO_ROOT_PASSWORD: ${MO_SECURITY_ADMIN_PASSWORD}
      MINIO_BROWSER_REDIRECT_URL: ${MINIO_BROWSER_REDIRECT_URL}
      MINIO_SERVER_URL: ${MINIO_SERVER_URL:-http://localhost:9090}
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9090/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    hostname: minio-01
    volumes:
      - minio-01-data1:/data1
      - minio-01-data2:/data2
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.docker.network=reverse-proxy-traefik_public
        - traefik.http.routers.minio-console.rule=Host(`${DOMAIN_NAME_HOST_TRAEFIK}`) && PathPrefix(`/minio-console`)
        - traefik.http.routers.minio-console.priority=100
        - traefik.http.routers.minio-console.service=minio-console-service
        - traefik.http.services.minio-console-service.loadbalancer.server.port=9001
        - traefik.http.middlewares.minio-console-stripprefix.stripprefix.prefixes=/minio-console/
        - traefik.http.routers.minio-console.middlewares=minio-console-stripprefix
        - traefik.http.routers.minio-console.tls=${TLS}

        - traefik.http.routers.minio-api.rule=Host(`${DOMAIN_NAME_HOST_TRAEFIK}`) && PathPrefix(`/minio-api`)
        - traefik.http.routers.minio-api.priority=100
        - traefik.http.routers.minio-api.service=minio-api-service
        - traefik.http.services.minio-api-service.loadbalancer.server.port=9090
        - traefik.http.middlewares.minio-api-stripprefix.stripprefix.prefixes=/minio-api/
        - traefik.http.routers.minio-api.middlewares=minio-api-stripprefix
        - traefik.http.routers.minio-api.tls=${TLS}
    networks:
      public:
      traefik:
networks:
  public:
    name: minio_public
    external: true
  traefik:
    name: reverse-proxy-traefik_public
    external: true

volumes:
  minio-01-data1:
  minio-01-data2:
