name: platform-e2e-tests
on:
  pull_request:
    types: [ready_for_review]
  push:
    tags:
      - "*"
  workflow_dispatch:
concurrency: e2e
jobs:
  provision-e2e-server:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      TF_VAR_PROJECT_NAME: platform-e2e-tests
      TF_VAR_INSTANCE_COUNT: 1
      TF_VAR_PUBLIC_KEY_PATH: key.pub
      TF_VAR_SUB_DOMAIN_NAME_CREATION_ENABLED: true
      TF_VAR_DOMAIN_NAME_CREATION_ENABLED: false
      TF_VAR_HOSTED_ZONE_ID: Z00782582NSP6D0VHBCMI
      TF_VAR_DOMAIN_NAME: jembi.cloud
      TF_VAR_SUBDOMAIN_NAMES: ${{ github.run_id }}.jembi.cloud *.${{ github.run_id }}.jembi.cloud
      TF_VAR_INSTANCE_TYPE: r5.2xlarge
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    defaults:
      run:
        working-directory: ./infrastructure/terraform
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - run: 'pwd && echo "$SSH_KEY" > key.pub'
        shell: bash
        env:
          SSH_KEY: ${{ secrets.DEPLOY_KEY_PUB }}
      - run: terraform init
      - run: terraform apply -auto-approve
      - name: Upload terraform state
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: tfstate
          path: infrastructure/terraform/terraform.tfstate
  configure-e2e-server:
    runs-on: ubuntu-latest
    needs: provision-e2e-server
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbooks/provision.yml
          directory: ./infrastructure/ansible
          key: ${{ secrets.DEPLOY_KEY }}
          vault_password: ${{ secrets.VAULT_PASSWORD }}
          inventory: |
            [leader]
            ${{ github.run_id }}.jembi.cloud name=node-1

            [managers]

            [workers]
          options: |
            --become
            --user=ubuntu
            --extra-vars @./inventories/development/group_vars/all.yml
  launch-platform:
    runs-on: ubuntu-latest
    needs: configure-e2e-server
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - run: ./get-cli.sh linux
      - run: ./build-image.sh
      - run: sudo sh -c 'echo "    ServerAliveInterval 30" >> /etc/ssh/ssh_config'
      - run: sudo sh -c 'echo "    ServerAliveCountMax 999" >> /etc/ssh/ssh_config'
      - run: sudo service ssh restart
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      - run: ssh-keyscan -H ${{ github.run_id }}.jembi.cloud >> ~/.ssh/known_hosts
      - run: ./remote-img-load.sh ${{ github.run_id }}.jembi.cloud
      - run: sed -i 's/domain/${{ github.run_id }}.jembi.cloud/g' .env.ci
      - run: DOCKER_HOST=ssh://ubuntu@${{ github.run_id }}.jembi.cloud ./platform-linux --env-file=.env.ci init
  destroy-e2e-server:
    runs-on: ubuntu-latest
    if: always()
    needs: [provision-e2e-server, configure-e2e-server, launch-platform]
    timeout-minutes: 15
    env:
      TF_VAR_PROJECT_NAME: platform-e2e-tests
      TF_VAR_INSTANCE_COUNT: 1
      TF_VAR_PUBLIC_KEY_PATH: key.pub
      TF_VAR_SUB_DOMAIN_NAME_CREATION_ENABLED: true
      TF_VAR_DOMAIN_NAME_CREATION_ENABLED: false
      TF_VAR_HOSTED_ZONE_ID: Z00782582NSP6D0VHBCMI
      TF_VAR_DOMAIN_NAME: jembi.cloud
      TF_VAR_SUBDOMAIN_NAMES: ${{ github.run_id }}.jembi.cloud *.${{ github.run_id }}.jembi.cloud
      TF_VAR_INSTANCE_TYPE: r5.2xlarge
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    defaults:
      run:
        working-directory: ./infrastructure/terraform
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - run: 'echo "$SSH_KEY" > key.pub'
        shell: bash
        env:
          SSH_KEY: ${{secrets.DEPLOY_KEY_PUB}}
      - name: Download terraform state
        uses: actions/download-artifact@v3
        with:
          name: tfstate
          path: infrastructure/terraform/
      - run: terraform init
      - run: terraform destroy -auto-approve
